import { Client } from "@modelcontextprotocol/sdk/client/index.js";
import { StreamableHTTPClientTransport } from "@modelcontextprotocol/sdk/client/streamableHttp.js";
const base = "http://127.0.0.1:5000";
const client = new Client({ name: "e2e-claude-sim", version: "1.0" });
await client.connect(new StreamableHTTPClientTransport(new URL(base + "/mcp/t/test-token")));
const tools = (await client.listTools()).tools;
console.log("tools:", tools.length, tools.map(t=>t.name).join(", "));
const call = async (name, args) => { const r = await client.callTool({ name, arguments: args }); const t = r.content?.find(c=>c.type==="text")?.text ?? ""; if (r.isError) console.log("ERR", name, t.slice(0,400)); return t; };
console.log((await call("list_pages", {})).slice(0, 300));
console.log((await call("get_seo", { page: "tours" })).slice(0, 300));
const t1 = await call("update_seo", { page: "tours", lang: "en", seo: { title: "Private Tours in Krabi — Amon Tour (2026 e2e)" }, commitMessage: "cms(seo): e2e test title /tours" });
console.log("update_seo ->", t1.slice(0, 400));
const t2 = await call("add_section", { page: "tours", type: "text", props: { title: "Nouveautés 2026 e2e", content: "<p>Hello from ChatGPT simulation.</p>" }, i18n: { fr: { title: "Nouveautés 2026 (fr)" } } });
console.log("add_section ->", t2.slice(0, 400));
const bad = await call("add_section", { page: "tours", type: "not_a_type", props: {} });
console.log("invalid ->", bad.slice(0, 200));
const prev = await call("preview_page", { page: "tours", lang: "fr" });
console.log("preview contains fr title:", prev.includes("Nouveautés 2026 (fr)"));
console.log((await call("publish_status", {})).slice(0, 300));
console.log((await call("list_tour_ninja_tours", {})).slice(0, 200));
await client.close();
