import { useState } from 'react';
import { useMutation, useQuery } from '@tanstack/react-query';
import { queryClient, apiRequest } from '@/lib/queryClient';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { RadioGroup, RadioGroupItem } from '@/components/ui/radio-group';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { useToast } from '@/hooks/use-toast';
import { Loader2 } from 'lucide-react';
import { useTranslation } from '@/contexts/TranslationContext';

interface AddPageModalProps {
  isOpen: boolean;
  onClose: () => void;
  onSuccess: (pageSlug: string) => void;
}

interface PageConfiguration {
  id: number;
  pageName: string;
  pageSlug: string;
  pageType: 'main' | 'secondary' | 'legal';
  isActive: boolean;
}

export function AddPageModal({ isOpen, onClose, onSuccess }: AddPageModalProps) {
  const { toast } = useToast();
  const { translations } = useTranslation();
  const [pageName, setPageName] = useState('');
  const [createMode, setCreateMode] = useState<'new' | 'duplicate' | 'legal'>('new');
  const [sourcePageId, setSourcePageId] = useState<string>('');

  const modal = translations?.admin?.editor?.pageMessages?.addPageModal || translations?.admin?.editor?.pages?.addPageModal;
  const t = {
    title: modal?.title || "Add a new page",
    description: modal?.description || "Create a new page or duplicate an existing page",
    createMode: modal?.createMode || "Creation mode",
    newBlankPage: modal?.newBlankPage || "Create a new blank page",
    duplicateFromExisting: modal?.duplicateFromExisting || "Duplicate from an existing page",
    createLegalPage: modal?.createLegalPage || "Create a legal page",
    pageToDuplicate: modal?.pageToDuplicate || "Page to duplicate",
    selectPage: modal?.selectPage || "Select a page",
    pageName: modal?.pageName || "Page name",
    pageNamePlaceholder: modal?.pageNamePlaceholder || "Ex: About",
    urlAutoGenerated: modal?.urlAutoGenerated || "The URL will be generated automatically from the name",
    cancel: modal?.cancel || "Cancel",
    add: modal?.add || "Add",
    creating: modal?.creating || "Creating...",
    success: modal?.success || "Success",
    pageCreated: modal?.pageCreated || "The page has been created successfully",
    error: modal?.error || "Error",
    pageNameRequired: modal?.pageNameRequired || "Page name is required",
    selectPageToDuplicate: modal?.selectPageToDuplicate || "Please select a page to duplicate",
    pageAlreadyExists: modal?.pageAlreadyExists || "A page with this name already exists. Please choose a different name.",
    createError: modal?.createError || "Unable to create the page"
  };

  const { data: existingPages = [] } = useQuery<PageConfiguration[]>({
    queryKey: ['/api/admin/page-configurations'],
    enabled: isOpen,
  });

  const createPageMutation = useMutation({
    mutationFn: async (data: { 
      pageName: string; 
      pageSlug: string;
      pageType: string;
      isActive: boolean;
      sourcePageId?: number;
    }) => {
      const response = await apiRequest('POST', '/api/admin/page-configurations', data);
      return response.json();
    },
    onSuccess: async (data: any) => {
      toast({
        title: t.success,
        description: t.pageCreated,
      });
      await queryClient.invalidateQueries({ queryKey: ['/api/admin/page-configurations'] });
      await queryClient.refetchQueries({ queryKey: ['/api/admin/page-configurations'] });
      
      onSuccess(data.pageSlug);
      handleClose();
    },
    onError: (error: any) => {
      toast({
        title: t.error,
        description: error.message || t.createError,
        variant: "destructive",
      });
    }
  });

  const handleSubmit = () => {
    if (!pageName.trim()) {
      toast({
        title: t.error,
        description: t.pageNameRequired,
        variant: "destructive",
      });
      return;
    }

    if (createMode === 'duplicate' && !sourcePageId) {
      toast({
        title: t.error,
        description: t.selectPageToDuplicate,
        variant: "destructive",
      });
      return;
    }

    let pageSlug = pageName
      .toLowerCase()
      .normalize('NFD')
      .replace(/[\u0300-\u036f]/g, '')
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-+|-+$/g, '');
    
    const existingSlugs = existingPages.map(p => p.pageSlug);
    
    if (existingSlugs.includes(pageSlug)) {
      toast({
        title: t.error,
        description: t.pageAlreadyExists,
        variant: "destructive",
      });
      return;
    }

    const data = {
      pageName,
      pageSlug,
      pageType: createMode === 'legal' ? 'legal' : 'secondary',
      isActive: createMode === 'legal' ? true : false,
      ...(createMode === 'duplicate' && sourcePageId ? { sourcePageId: parseInt(sourcePageId) } : {})
    };

    createPageMutation.mutate(data);
  };

  const handleClose = () => {
    setPageName('');
    setCreateMode('new');
    setSourcePageId('');
    onClose();
  };

  return (
    <Dialog open={isOpen} onOpenChange={handleClose}>
      <DialogContent className="sm:max-w-[500px]">
        <DialogHeader>
          <DialogTitle>{t.title}</DialogTitle>
          <DialogDescription>
            {t.description}
          </DialogDescription>
        </DialogHeader>
        
        <div className="grid gap-4 py-4">
          <div className="space-y-3">
            <Label>{t.createMode}</Label>
            <RadioGroup 
              value={createMode} 
              onValueChange={(value) => setCreateMode(value as 'new' | 'duplicate' | 'legal')}
            >
              <div className="flex items-center space-x-2">
                <RadioGroupItem value="new" id="new" />
                <Label htmlFor="new" className="font-normal cursor-pointer">
                  {t.newBlankPage}
                </Label>
              </div>
              <div className="flex items-center space-x-2">
                <RadioGroupItem value="duplicate" id="duplicate" />
                <Label htmlFor="duplicate" className="font-normal cursor-pointer">
                  {t.duplicateFromExisting}
                </Label>
              </div>
              <div className="flex items-center space-x-2">
                <RadioGroupItem value="legal" id="legal" />
                <Label htmlFor="legal" className="font-normal cursor-pointer">
                  {t.createLegalPage}
                </Label>
              </div>
            </RadioGroup>
          </div>

          {createMode === 'duplicate' && (
            <div className="space-y-2">
              <Label htmlFor="source-page">{t.pageToDuplicate}</Label>
              <Select value={sourcePageId} onValueChange={setSourcePageId}>
                <SelectTrigger id="source-page">
                  <SelectValue placeholder={t.selectPage} />
                </SelectTrigger>
                <SelectContent>
                  {existingPages.map((page) => (
                    <SelectItem key={page.id} value={page.id.toString()}>
                      {page.pageName}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
          )}

          <div className="space-y-2">
            <Label htmlFor="page-name">{t.pageName}</Label>
            <Input
              id="page-name"
              value={pageName}
              onChange={(e) => setPageName(e.target.value)}
              placeholder={t.pageNamePlaceholder}
              disabled={createPageMutation.isPending}
            />
            <p className="text-sm text-gray-500">
              {t.urlAutoGenerated}
            </p>
          </div>
        </div>

        <DialogFooter>
          <Button 
            variant="outline" 
            onClick={handleClose}
            disabled={createPageMutation.isPending}
          >
            {t.cancel}
          </Button>
          <Button 
            onClick={handleSubmit}
            disabled={createPageMutation.isPending}
          >
            {createPageMutation.isPending ? (
              <>
                <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                {t.creating}
              </>
            ) : (
              t.add
            )}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
